FROM python:3.14-slim

ENV PYTHONUNBUFFERED=1

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /retrieve-lms

ENV VENV_PATH=/retrieve-lms/.venv
RUN python -m venv $VENV_PATH
ENV PATH="$VENV_PATH/bin:$PATH"

COPY --chown=app:app requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY --chown=app:app . /retrieve-lms

EXPOSE 8000
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
