FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
ENV VENV_PATH=/app/.venv

RUN useradd -ms /bin/sh -u 1001 app \
    && mkdir -p /app \
    && chown -R app:app /app

USER app
WORKDIR /app

RUN python -m venv $VENV_PATH
ENV PATH="$VENV_PATH/bin:$PATH"

COPY --chown=app:app frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=app:app frontend/ .

EXPOSE 8001
CMD ["python", "main.py"]
