import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from alembic.operations import ops
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core.config import settings
from core.database import Base
from schemas.models import *

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url() -> str:
    return settings.database_url or config.get_main_option("sqlalchemy.url")


# --- inject IF NOT EXISTS / IF EXISTS into autogenerated ops ---
_IF_NOT_EXISTS_OPS = (ops.CreateTableOp, ops.CreateIndexOp, ops.AddColumnOp)
_IF_EXISTS_OPS = (
    ops.DropTableOp,
    ops.DropIndexOp,
    ops.DropColumnOp,
    ops.DropConstraintOp,
)


def _walk(op_list):
    for op in op_list:
        if isinstance(op, _IF_NOT_EXISTS_OPS):
            op.if_not_exists = True
        elif isinstance(op, _IF_EXISTS_OPS):
            op.if_exists = True
        # recurse into nested containers (e.g. ModifyTableOps holds per-table ops)
        nested = getattr(op, "ops", None)
        if nested:
            _walk(nested)


def process_revision_directives(context, revision, directives):
    script = directives[0]
    if script.upgrade_ops:
        _walk(script.upgrade_ops.ops)
    if script.downgrade_ops:
        _walk(script.downgrade_ops.ops)


def run_migrations_offline():
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
        compare_type=True,
        compare_server_default=True,
        process_revision_directives=process_revision_directives,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_schemas=True,
            compare_type=True,
            compare_server_default=True,
            process_revision_directives=process_revision_directives,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
