"""Added member requests for courses that require a join request

Revision ID: 4bbe11019a9b
Revises: 914b8158547f
Create Date: 2026-10-02 16:11:03.394202

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bbe11019a9b"
down_revision: Union[str, Sequence[str], None] = "914b8158547f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "course_id", name="uq_member_requests_user_course"
        ),
        if_not_exists=True,
    )
    op.create_index(
        "ix_members_requests_user_id_course_id",
        "member_requests",
        ["user_id", "course_id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_members_requests_user_id_course_id",
        table_name="member_requests",
        if_exists=True,
    )
    op.drop_table("member_requests", if_exists=True)
    # ### end Alembic commands ###
