"""Added an flat to enable or disable generative fuctions inside a course

Revision ID: 90e8edb95205
Revises: 95ff06756c92
Create Date: 2026-09-27 23:03:22.098178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e8edb95205'
down_revision: Union[str, Sequence[str], None] = '95ff06756c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('llm_enabled', sa.Boolean(), nullable=False), if_not_exists=True)
    op.drop_index(op.f('ix_members_user_id_course_id'), table_name='members', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_user_id_course_id'), 'members', ['user_id', 'course_id'], unique=False, if_not_exists=True)
    op.drop_column('courses', 'llm_enabled', if_exists=True)
    # ### end Alembic commands ###
