"""Added members role to the members table for the courses

Revision ID: 914b8158547f
Revises: 90e8edb95205
Create Date: 2026-10-02 15:53:46.633442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "914b8158547f"
down_revision: Union[str, Sequence[str], None] = "90e8edb95205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "members",
        sa.Column(
            "user_role",
            sa.Enum(
                "teacher",
                "substitute",
                "student",
                name="member_role",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        if_not_exists=True,
    )
    op.create_index(
        "ix_members_user_id_role_course_id",
        "members",
        ["user_id", "user_role", "course_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_unique_constraint(
        "uq_members_user_role", "members", ["user_id", "user_role"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_members_user_role", "members", type_="unique", if_exists=True
    )
    op.drop_index(
        "ix_members_user_id_role_course_id", table_name="members", if_exists=True
    )
    op.drop_column("members", "user_role", if_exists=True)
    # ### end Alembic commands ###
