"""Added a Courses and a Members table

Revision ID: 95ff06756c92
Revises: ef6dc4b13e8c
Create Date: 2026-09-22 15:20:41.752764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ff06756c92'
down_revision: Union[str, Sequence[str], None] = 'ef6dc4b13e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    if_not_exists=True
    )
    op.create_index('ix_courses_active_id', 'courses', ['is_active', 'id'], unique=False, if_not_exists=True)
   
   
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uix_members_user_id_course_id'),
    if_not_exists=True
    )
    op.create_index('ix_members_user_id_course_id', 'members', ['user_id', 'course_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_members_user_id_course_id', table_name='members', if_exists=True)
    op.drop_table('members', if_exists=True)
    op.drop_index('ix_courses_active_id', table_name='courses', if_exists=True)
    op.drop_table('courses', if_exists=True)
    # ### end Alembic commands ###
